# Permalinks
permalink:           pretty

# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             pk69@ngs.ru
# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/krugersu/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
pages_list:
  О блоге: '/about.md'
  Архив записей: '/archive'
  Лента: '/atom.xml'
